export const AUTH_USER = 'auth_user',
             SHOW_PURCHASES = 'show_purchases',
             UNAUTH_USER = 'unauth_user',
             FORGOT_PASSWORD_REQUEST = 'forgot_password_request',
             RESET_PASSWORD_REQUEST = 'reset_password_request',
             RECEIVE_REFUND_CONFIRMATION = 'receive_refund_confirmation',
             ERROR = 'error',
             SAVE_ADDRESS = 'save_address',
             SAVE_WISHLIST = 'save_wishlist',
             WISHLIST_UPDATING = 'wishlist_updating',
             CLEAR_ERRORS = 'clear_errors',
             RECEIVE_PLAID_CONFIG = 'receive_plaid_config',
             OPEN_MODAL = 'open_modal',
             CLOSE_MODAL = 'close_modal',
             RECEIVE_USER_SETUP = 'receive_user_setup',
             PROTECTED_TEST = 'protected_test';

